# Site settings
title: Interactivos?'16
description: Água e Autonomia

baseurl: "/2016"
url: "https://interactivos.silo.org.br"
permalink: /:year/:month/:day/:title/

#########################################

# Build settings
markdown: kramdown
port: 4455
theme: null
